services:
  douban-api-go:
    image: ghcr.io/haigeek/douban-api-go:latest
    container_name: douban-api-go
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      TZ: Asia/Shanghai
      DOUBAN_COOKIE: ${DOUBAN_COOKIE:-}
      DOUBAN_API_LIMIT_SIZE: ${DOUBAN_API_LIMIT_SIZE:-3}
      BASIC_USER: ${BASIC_USER:-}
      BASIC_PASS: ${BASIC_PASS:-}
    command:
      - /usr/bin/douban-api-go
      - --host
      - 0.0.0.0
      - --port
      - "80"
      - --limit
      - "${DOUBAN_API_LIMIT_SIZE:-3}"
      - --cookie
      - "${DOUBAN_COOKIE:-}"
      - --basic-user
      - "${BASIC_USER:-}"
      - --basic-pass
      - "${BASIC_PASS:-}"
